[tox]
envlist = py310,py311,py312,py313,quality
isolated_build = true

[testenv]
extras = dev
commands = pytest

[testenv:quality]
basepython = python3.12
extras = dev
commands =
	isort --check-only habitipy tests
	black --check habitipy tests
	ruff check habitipy tests
	mypy habitipy